# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d27af24864cec85735bfb39e3f16f32c93e24dfef6a96d4c1e786733937990c7e5bb1d2511039f5f468a79af59b6590ea67b72aacfc534bc8d658880edad531

test:
  secret_key_base: 017eaf0cb041439f8fd3dc7645e5782cf74f6da5ad87835d4389a00fba19faf93801ab831f3b0a63a2e55b13e5bf4e4e5c3b3d031f96b10dc9d574a23eb89ab3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
